- name: install common packages
  yum: name={{item}} state=installed
  with_items:
    - htop
    - nmap
    - tcpdump
    - lynx
    - vim
    - rsync
    - openssh-clients
    - tmux
    - screen
    - bind-utils
    - curl
    - wget
    - nfs-utils
    - net-tools
    - telnet
    - lvm2
    - zip
    - unzip
    - sudo
    - lsof
    - nmap-ncat
    - iperf
    - mtr
    - nmap-ncat
    - bzip2
    - sysstat
    - samba-client
    - ntfs-3g
    - ansible
    - fuse-sshfs
    - cifs-utils
    - epel-release
    - ncftp
    - lftp
    - mailx
    - git
