- hosts: all
  name: do stuff common to all servers for your average at-home VM
  become: yes
  become_method: sudo

  roles:
    - user_rcfiles
    - standard_packages
    - fail2ban
    - fail2ban-sshd
    - fail2ban-standard_unix_auth
