- hosts: all
  name: do stuff common to all servers for your average at-home VM
  become: yes
  become_method: sudo

  roles:
    - user_rcfiles
    - standard_packages
    - centos_update
    - fail2ban
    - fail2ban-sshd
    - fail2ban-standard_unix_auth

- hosts: internal,webservers,mailservers,ovirt,workstation
  name: disable firewalld
  become: yes
  become_method: sudo

  roles:
    - disable_firewalld

- hosts: ovirt
  name: install ovirt stuff
  become: yes
  become_method: sudo

  roles:
    - ovirt

- hosts: workstation
  name: install build tools for workstations
  become: yes
  become_method: sudo

  roles:
    - build_tools
    - fish_shell

- hosts: webservers
  name: install stuff for webservers
  become: yes
  become_method: sudo

  roles:
    - httpd
    - fail2ban-httpd
