- hosts: internal,external,ovirt
  name: do stuff common to all servers for your average at-home VM
  become: yes
  become_method: sudo

  roles:
    - user_rcfiles
    - standard_packages
    - disable_firewalld
    - centos_update
    - fail2ban

- hosts: external-withfirewalld
  name: do stuff common to all servers for your average at-home VM (keeping firewalld)
  become: yes
  become_method: sudo

  roles:
    - user_rcfiles
    - standard_packages
    - centos_update
    - fail2ban

- hosts: ovirt
  name: install ovirt stuff
  become: yes
  become_method: sudo

  roles:
    - ovirt
