- name: install httpd
  yum: name={{item}} state=installed
  with_items:
    - httpd

- name: ensure httpd is running (and enable it at boot)
  service: name=httpd state=started enabled=yes

#- include: fail2ban.yml
